#!/usr/bin/env bash
# shellcheck disable=SC2162,SC2317

##  GitHub Script: https://github.com/slyfox1186/wsl2-kernel-build-script/blob/main/build-kernel
##  Purpose: Build Official WSL2 Kernels
##  Updated: 03.12.24
##  Script version: 2.9

show_help() {
    echo "Usage: $(basename "$0") [options]"
    echo "Options:"
    echo "  -h, --help                  Show this help message."
    echo "  -v, --version VERSION       Set a custom version number of the WSL2 kernel to install."
    echo "  -o, --output-directory DIRECTORY  Specify where the vmlinux file should be placed after build."
}

version_specified=false
specific_version=""
output_directory=""
version_type=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -v|--version)
            version_specified=true
            specific_version="linux-msft-wsl-$2"
            shift # past argument
            shift # past value
            ;;
        -o|--output-directory)
            output_directory=$2
            shift # past argument
            shift # past value
            ;;
        *)
            shift # past argument
            ;;
    esac
done

if [ "$EUID" -ne 0 ]; then
    echo "You must run this script with root/sudo."
    exit 1
fi

# Prompting the user for input if no version specified
if ! $version_specified; then
    while true; do
        echo "Choose the WSL2 kernel version to download and install:"
        echo
        echo "1. Linux series 6 kernel"
        echo "2. Linux series 5 kernel"
        echo "3. Specific version"
        echo "4. Exit"
        echo
        read -p "Enter your choice (1-4): " choice

        case $choice in
            1)
                version_type="6"
                break
                ;;
            2)
                version_type="5"
                break
                ;;
            3)
                read -p "Enter the version numbers (e.g., 5.15.90.1): " user_input
                specific_version="linux-msft-wsl-$user_input"
                version_specified=true
                break
                ;;
            4)
                echo "Exiting the script."
                exit 0
                ;;
            *)
                echo "Invalid choice. Please try again."
                ;;
        esac
    done
fi

# Ensure the directory for 'vmlinux' is prepared.
if [ -z "$output_directory" ]; then
    script_dir="$PWD" # Use current directory if no output directory is specified
else
    script_dir="$output_directory"
    mkdir -p "$script_dir" # Create output directory if it does not exist
fi

master_dir="/tmp/wsl2-build-script" # Master parent directory
cwd="$master_dir/wsl2-kernel-build-script"
error_log="$master_dir/error.log"

# Create the master parent directory and the build directory within it
mkdir -p "$cwd"
cd "$cwd" || exit 1

# Set compiler optimizations
CC="gcc"
CXX="g++"
CFLAGS="-g -O3 -march=native"
CXXFLAGS="$CFLAGS"

export CC CXX CFLAGS CXXFLAGS

announce_options() {
    # Announce options after all inputs have been processed
    echo "Final script configuration:"
    echo "Specific version specified: $version_specified"
    if $version_specified; then
        echo "Specific version: $specific_version"
    else
        echo "Version: Using the latest available version"
    fi
    echo "Output directory: ${output_directory:-"Default directory ($PWD)"}"
}

install_required_packages() {
    local missing_packages=""
    local pkgs=(
        aria2 bc bison build-essential cmake curl debootstrap dwarves flex g++
        g++-s390x-linux-gnu gcc gcc-s390x-linux-gnu gdb-multiarch git libcap-dev
        libelf-dev libncurses-dev libncurses5 libncursesw5 libncursesw5-dev
        libssl-dev make pkg-config python3 qemu-system-misc qemu-utils rsync wget
    )

    for pkg in "${pkgs[@]}"; do
        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
            missing_packages+="$pkg "
        fi
    done

    if [ -n "$missing_packages" ]; then
        echo
        echo "Installing missing packages: $missing_packages"
        echo
        sudo apt-get -y install $missing_packages
    else
        echo
        echo "All APT packages are already installed."
        echo
    fi
}

download_file() {
    local url=$1
    local output_file=$2

    if [ -s "$output_file" ]; then
        echo "File $output_file already exists and is not empty. Skipping download."
        return 0
    fi

    if command -v wget &> /dev/null; then
        echo "Downloading with wget..."
        wget --show-progress -cqO "$output_file" "$url"
    else
        echo "wget is not installed. Please install wget."
        exit 1
    fi
}

get_latest_release_version() {
    local version_type=$1
    local url="https://github.com/microsoft/WSL2-Linux-Kernel/tags/"
    local pattern="linux-msft-wsl-$version_type\\.[0-9]+\\.[0-9]+\\.[0-9]+"

    curl -s "$url" | grep -oP "$pattern" | head -1
}

build_kernel_without_progress() {
    echo "Installing the WSL2 Kernel"
    echo "========================================="
    if ! echo "yes" | make "-j$(nproc --all)" KCONFIG_CONFIG="Microsoft/config-wsl" 2>>"$error_log"; then
        echo "Build process terminated with errors. Please check the error log below:"
        cat "$error_log"
        return 1
    fi
    return 0
}

install_kernel() {
    clear
    announce_options
    install_required_packages

    if [ -n "$specific_version" ]; then
        version="$specific_version"
    else
        version=$(get_latest_release_version "$version_type")
    fi

    echo "Downloading kernel version $specific_version..."

    if [ -z "$version" ]; then
        echo "Failed to find the latest version. Exiting."
        echo
        exit 1
    fi

    echo "Successfully downloaded the source code file \"$version\""
    echo

    tar_file="$master_dir/$program_name-$version.tar.gz"
    download_url="https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/$version.tar.gz"

    download_file "$download_url" "$tar_file"

    extract_dir="$master_dir/$program_name-$version"
    [ -d "$extract_dir" ] && rm -rf "$extract_dir"

    mkdir -p "$extract_dir"
    if ! tar -zxf "$tar_file" -C "$extract_dir" --strip-components 1; then
        echo "Failed to extract the archive. Deleting the corrupt archive."
        rm -f "$tar_file"
        echo
        echo "The archive file has been deleted due to extraction failure."
        echo "Please run the script again to fix the issue."
        exit 1
    fi

    cd "$extract_dir" || exit 1
    echo "Building the kernel..."
    echo
    if ! build_kernel_without_progress; then
        rm -rf "$extract_dir"
        echo "Error log:"
        cat "$error_log"
        echo "Kernel build failed. Please check the error log above for more information."
        return 1
    else
        find_vmlinux="$(find $PWD -type f -name 'vmlinux' | head -n1)"
        if [ -f "$find_vmlinux" ]; then
            mv "$find_vmlinux" "$script_dir/vmlinux"
            echo "Kernel build successful. vmlinux moved to the specified output directory: $script_dir"
            echo

            read -p "Do you want to delete the build directory? (y/n): " user_choice
            if [ "$user_choice" = "y" ]; then
                rm -fr "$master_dir"
                echo "Build directory cleaned up."
                echo
            else
                echo "Build directory retained as per user choice."
                echo
            fi
        else
            echo "Error: vmlinux file not found. Please check the build process."
            return 1
        fi
    fi
}

install_kernel
